name: casino_app
description: Casino App
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  socket_io_client: ^2.0.0
  http: ^1.0.0
  shared_preferences: ^2.0.0

flutter:
  uses-material-design: true
